### ISSUE TITLE
Fun for your java comply 

### ISSUE THREAD

**Issue by constantinedev** [SchelleyYuki/m1-test#1]
1. the funny things is why do you run apache with Java?
2. post together with your speed test photo maybe better
3. you make not very know about the power of i9
   as you are using the notebook Lv CPU if you get the new i9 10000K
   ARM will still lost!
It doesn't means I'm the intel fan's but if you really wanna make the good test you should peer with ADM
I'm also the hardware and software engineer.
It doesn't means you are going the wrong way we most care more about the probuct running on the client site for sale.
the JDK of MSFT cuz same get some bug for the other process.
May be this is for your test, but it should not going to work for the stable developer.

**Comment by SchelleyYuki** [comment]
Not sure if you fully grasped my video, but it was not "run apache with Java": it was compiling https://github.com/apache/commons-lang.

Earlier today I run the experiment again, using Zulu Java 8 on _both_ computers. The results were highly consistent with the final result in my video. 

I'm not sure if you got upset by the test result in my video, but I'd prefer if you put in some actual work doing some benchmark by yourself and posting them here, like [this one](https://github.com/SchelleyYuki/m1-test/issues/2).
