### ISSUE TITLE
hyper or terminus ?

### ISSUE THREAD

**Issue by gaoming714** [SchelleyYuki/m1-test#6]
I remember you recommended a terminal hyper in a video, and I guess you should customize the software appropriately because the default settings are a little too simple. Can you tell me how you customize it?

In addition, I recently found a similar terminal terminus, also very useful.
https://github.com/Eugeny/terminus

![image](https://user-images.githubusercontent.com/7444968/102743562-a7892000-4392-11eb-818a-411fa2f04b92.png)

**Comment by SchelleyYuki** [comment]
@gaoming714 , The Hyper plugins I installed are listed [in this video staring from 7:08](https://youtu.be/yLJowy8pa1s?t=428). 

Also, I have the following setting in my `.hyper.js` config file:

```
copyOnSelect: true,
```

 Thanks for sharing Terminus! It feels sleek!

**Comment by gaoming714** [comment]
Thank you for your reply, I seem to be beginning to appreciate hyper's style,
