### ISSUE TITLE
Yes, U find a bug...No, D8ger

### ISSUE THREAD

**Issue by caofanCPU** [SchelleyYuki/m1-test#7]
我是帝八哥, 过来和你建立一个连接，哈哈

**Comment by SchelleyYuki** [comment]
@caofanCPU 哈哈😄, hello!

**Comment by caofanCPU** [comment]
@SchelleyYuki 
Hi, nice to receive your response! Does this mean that our connection has got a successful landing 😏?

A few months ago, I have developed a  plugin named [**LaoYouTiao**](https://plugins.jetbrains.com/plugin/15255-laoyoutiao)  😄 .
Specially for a full stack programmer, it should help you save some time. I hope you can try it.

And recently I've been captured by a [beautiful lady](https://www.youtube.com/watch?v=7NgW3GhZSpA). Do you know how to get rid of her 🤣?

**Comment by caofanCPU** [comment]
Done.
